GLOBAL SUB GLOBAL_DEF()
    ' system_state
    GLOBAL CONST SYS_BOOT = 0
    GLOBAL CONST SYS_BUS_INIT = 1
    GLOBAL CONST SYS_SERVO_READY = 2
    GLOBAL CONST SYS_HOMING = 3
    GLOBAL CONST SYS_READY = 4  ' 已回零，可运动
    GLOBAL CONST SYS_RUNNING = 5
    GLOBAL CONST SYS_PAUSED = 6
    GLOBAL CONST SYS_ERROR = 8
    GLOBAL CONST SYS_ESTOP = 9  ' 急停

    ' event id(事件)
    GLOBAL CONST EVENT_IDLE         = 0
    GLOBAL CONST EVENT_HOME         = 1
    GLOBAL CONST EVENT_HOME_DONE    = 2
    GLOBAL CONST EVENT_JOINT        = 3
    GLOBAL CONST EVENT_JOINT_DONE   = 4
    GLOBAL CONST EVENT_CART_JOG     = 5
    GLOBAL CONST EVENT_CART_JOG_DONE= 6
    GLOBAL CONST EVENT_TRAJ         = 7
    GLOBAL CONST EVENT_TRAJ_DONE    = 8
    GLOBAL CONST EVENT_STOP         = 9
    GLOBAL CONST EVENT_ERROR_RESET  = 10
    GLOBAL CONST EVENT_ESTOP        = 99

    ' task id(额外开启的任务号)
    GLOBAL CONST TASK_HOEM = 1
    GLOBAL CONST TASK_JOINT = 2
    GLOBAL CONST TASK_CATR_JOG = 3
    GLOBAL CONST TASK_TRAJ = 4

    ' motion_mode
    GLOBAL CONST MODE_IDLE = 0  ' 空闲
    GLOBAL CONST MODE_JOINT_MANUAL = 1  ' 手动控制
    GLOBAL CONST MODE_HOME = 2
    GLOBAL CONST MODE_CART_JOG = 3  ' 笛卡尔方向点动
    GLOBAL CONST MODE_TRAJECTORY = 4
    GLOBAL CONST MODE_SENSOR_CLOSED = 5

    ' cmd_id
    GLOBAL CONST CMD_NONE = 0  ' 无命令
    GLOBAL CONST CMD_JOINT_MOVE_REL = 1  ' 单轴相对移动
    GLOBAL CONST CMD_JOINT_MOVE_ABS = 2
    GLOBAL CONST CMD_JOINT_JOG_START = 3  ' 单轴连续点动开始
    GLOBAL CONST CMD_JOINT_STOP = 4  ' 单轴停止
    GLOBAL CONST CMD_HOME = 10
    GLOBAL CONST CMD_CART_JOG_START = 20
    GLOBAL CONST CMD_CART_JOG_STOP = 21
    GLOBAL CONST CMD_TRAJ_START = 30
    GLOBAL CONST CMD_TRAJ_PAUSE = 31
    GLOBAL CONST CMD_TRAJ_RESUME = 32  ' 轨迹（暂停后）恢复继续
    GLOBAL CONST CMD_TRAJ_STOP = 33
    GLOBAL CONST CMD_CL_START = 40
    GLOBAL CONST CMD_CL_STOP = 41
    GLOBAL CONST CMD_STOP = 90
    GLOBAL CONST CMD_ESTOP = 99  ' 急停请求

    ' State flag of data
    GLOBAL CONST F_DataUpdate = 1
    GLOBAL CONST F_DataUsed = 2
    GLOBAL CONST F_DataBlank = 3

    ' modbus reg config
    GLOBAL CONST REG_PC_HEARTBEAT = 0  ' Qt心跳计数？
    GLOBAL CONST REG_CMD_SEQ = 1  ' 命令序号计数，每发一套命令+1
    GLOBAL CONST REG_CMD_ID = 2  ' 命令类型
    GLOBAL CONST REG_CMD_STATE = 3  ' 0空闲，1接收，2执行中，3完成，4错误
    GLOBAL CONST REG_CMD_ERROR = 4
    GLOBAL CONST REG_SYSTEM_STATE = 5
    GLOBAL CONST REG_MOTION_MODE = 6
    GLOBAL CONST REG_SAFETY_STATE = 7
    GLOBAL CONST REG_ACTIVE_TASK = 8
	GLOBAL CONST REG_TRACE_CMD_STATE_BEGIN = 50
	GLOBAL CONST REG_JOG_CMD_STATE_BEGIN = 70
    GLOBAL CONST REG_JOINT_CMD_STATE_BEGIN = 80
    GLOBAL CONST REG_EVENT_BEGIN = 90
	GLOBAL CONST REG_EVENT_L0  = 90
	GLOBAL CONST REG_EVENT_L1  = 91
	GLOBAL CONST REG_EVENT_L2  = 92

    ' table id config
    GLOBAL CONST TABLE_JOINT_CMD_BEGIN = 300

    ' error code
    GLOBAL CONST ERR_OK                = 0
    GLOBAL CONST ERR_UNKNOWN_CMD       = 1001
    GLOBAL CONST ERR_MODE_BUSY         = 1002
    GLOBAL CONST ERR_SYSTEM_NOT_READY  = 1003
    GLOBAL CONST ERR_NEED_HOME         = 1004
    GLOBAL CONST ERR_SAFETY_ACTIVE     = 1005
    GLOBAL CONST ERR_TASK_START_FAIL   = 1006

    ' other config para
    GLOBAL CONST MAX_EVENT_LEVEL = 3
    GLOBAL CONST NUM_JOINT_DATA_GROUP = 5
	GLOBAL CONST NUM_JOG_DATA_GROUP = 5
	GLOBAL CONST NUM_TRACE_DATA_GROUP = 10
    GLOBAL CONST JOINT_CMD_SIZE = 7


END SUB

GLOBAL SUB REG_CLEAR()
	LOCAL i
	FOR i = 0 TO (NUM_JOINT_DATA_GROUP - 1) STEP 1
		MODBUS_REG(REG_JOINT_CMD_STATE_BEGIN + i) = 0
	NEXT
	
	FOR i = 0 TO (NUM_JOG_DATA_GROUP - 1) STEP 1
		MODBUS_REG(REG_JOG_CMD_STATE_BEGIN + i) = 0
	NEXT
	
	FOR i = 0 TO (NUM_TRACE_DATA_GROUP - 1) STEP 1
		MODBUS_REG(REG_TRACE_CMD_STATE_BEGIN + i) = 0
	NEXT
	
	
END SUB